Refactored zkl, zkllong and descendant functions. Added new ones.

diff --git a/zekyll b/zekyll
--- a/zekyll
+++ b/zekyll
@@ -184,6 +184,49 @@ ZKLCOL=(
 
     reply=( "$user" "$plugin" "$zekyll" )
 
+    [[ "$user" = "_unknown" || "$plugin" = "_unknown" || "$zekyll" = "_unknown" ]] && return 1
+
+    return 0
+}
+
+#
+# Used for long zekylls, i.e. the ones with description per zekyll:
+#
+# zkllong psprint/zkl:ac8 These are prompt settings
+# zkllong psprint:ac8 These are prompt settings
+# zkllong ac8 These are prompt settings
+#
+# Will use $ZKL_CUR_PLUGIN and $ZKL_CUR_USER if the values aren't
+# provided with zekyll
+#
+-zkl-any2-to-user-plugin-zekyll-desc() {
+    local user plugin zekyll desc
+    if [[ "$1" = [a-zA-Z0-9]##:[a-zA-Z0-9]* ]]; then
+        user="${1%:*}"
+        1="${1#*:}"
+    elif [[ "$1" = [a-zA-Z0-9]##/[a-zA-Z0-9]##:[a-zA-Z0-9]* ]]; then
+        user="${1%/*}"
+        plugin="${${1#*/}%:*}"
+        1="${1#*:}"
+    fi
+
+    [ -z "$user" ] && user="$ZKL_CUR_USER"
+    [[ "$user" = "_unknown" || -z "$user" ]] && -zkl-error "Error: unknown user" && return 1
+
+    [ -z "$plugin" ] && plugin="$ZKL_CUR_PLUGIN"
+    [[ "$plugin" = "_unknown" || -z "$plugin" ]] && -zkl-error "Error: unknown plugin" && return 1
+
+    # Obtain zekyll and desc
+    local input="${(j: :)@}"
+    desc="${input//(#s)(#b)[a-zA-Z0-9] #[a-zA-Z0-9] #[a-zA-Z0-9] #(*)/${match[1]}}"
+    [ "$desc" = "$input" ] && -zkl-error "Error: Improper long input string, cannot determine description" && return 1
+
+    local zekyll
+    zekyll="${input//(#s)(#b)([a-zA-Z0-9]) #([a-zA-Z0-9]) #([a-zA-Z0-9])*/${match[1]}${match[2]}${match[3]}.}"
+    [ "$zekyll" = "$input" ] && -zkl-error "Error: Improper long input string, cannot determine zekyll" && return 1
+    zekyll="${zekyll%?}"
+    
+    reply=( "$user" "$plugin" "$zekyll" "$desc" )
     return 0
 }
 
@@ -295,6 +338,39 @@ ZKLCOL=(
     fi
 }
 
+#
+# Typical actions on start of input:
+# - preparing home directory
+# - decoding input for repository and zekyll data
+# - updating repository
+# - detecting if "update only" mode is done
+# - signaling inproper input and update mode
+#
+# Has two modes, zkl and zkllong. Input differs for both of them.
+# For the first input, reffer to -zkl-any-to-user-plugin and for
+# the second one to -zkl-any2-to-user-plugin-zekyll-desc.
+#
+-zkl-start-zekyll-input() {
+    -zkl-prepare-home
+
+    if [ "$1" = "zkl" ]; then
+        shift
+        -zkl-any-to-user-plugin-zekyll "$1" "$2" "$3" || return 2
+    elif [ "$1" = "zkllong" ]; then
+        shift
+        -zkl-any2-to-user-plugin-zekyll-desc "$@" || return 2
+    else
+        return 1
+    fi
+
+    local -a tmp
+    tmp=( "${reply[@]}" )
+    -zkl-repo-preamble "${reply[1]}" "${reply[2]}"
+    reply=( "${tmp[@]}" )
+
+    [ "$ZKL_UPDATE_ONLY" = "1" ] && return 1
+    return 0
+}
 # 1}}}
 
 #
@@ -511,21 +587,9 @@ zkl() {
 
     [ "$ZKL_YES" = "NO" ] && return
 
-    #
-    # Repo management
-    #
-
-    -zkl-prepare-home
-    -zkl-any-to-user-plugin-zekyll "$1" "$2" "$3"
+    # Strictly, this will propagate error code from -zkl-start-zekyll-input
+    -zkl-start-zekyll-input "zkl" "$1" "$2" "$3" || return
     local user="${reply[-3]}" plugin="${reply[-2]}" zekyll="${reply[-1]}"
-
-    -zkl-repo-preamble "$user" "$plugin"
-
-    [ "$ZKL_UPDATE_ONLY" = "1" ] && return
-
-    #
-    # Zekylls verification and preprocessing
-    #
 
     # Allow underscores - remove them now
     zekyll="${zekyll//_/}"
@@ -572,35 +636,9 @@ zkllong() {
 
     [ "$ZKL_YES" = "NO" ] && return
 
-    -zkl-prepare-home
-
-    local user="$ZKL_CUR_USER"
-    [ "$user" = "_unknown" ] && -zkl-error "Error: unknown user" && return
-
-    local plugin="$ZKL_CUR_PLUGIN"
-    [ "$plugin" = "_unknown" ] && -zkl-error "Error: unknown plugin" && return
-
-    if [[ "$1" = [a-zA-Z0-9]##:[a-zA-Z0-9]* ]]; then
-        user="${1%:*}"
-        1="${1#*:}"
-    elif [[ "$1" = [a-zA-Z0-9]##/[a-zA-Z0-9]##:[a-zA-Z0-9]* ]]; then
-        user="${1%/*}"
-        plugin="${1#*/}"
-        plugin="${plugin%:*}"
-        1="${1#*:}"
-    fi
-
-    -zkl-repo-preamble "$user" "$plugin"
-
-    [ "$ZKL_UPDATE_ONLY" = "1" ] && return
-
-    # Obtain zekyll (single one)
-    local input="$*"
-    local desc
-    desc="${input//(#b)[a-zA-Z0-9] #[a-zA-Z0-9] #[a-zA-Z0-9](*)/${match[1]}}"
-    desc="${desc## ##}"
-    local zekyll
-    zekyll="${input//(#b)([a-zA-Z0-9]) #([a-zA-Z0-9]) #([a-zA-Z0-9])*/${match[1]}${match[2]}${match[3]}}"
+    # Strictly, this will propagate error code from -zkl-start-zekyll-input
+    -zkl-start-zekyll-input "zkllong" "$@" || return
+    local user="${reply[1]}" plugin="${reply[2]}" zekyll="${reply[3]}" desc="${reply[4]}"
 
     -zkl-pinfo2 "\nProcessing (long) for user $user, plugin $plugin\n"
 
@@ -623,7 +661,7 @@ zkllong() {
     ZKL_EMIT_SECTIONS+=( "$section" )
     ZKL_EMIT_REPOS+=( "${user}---${plugin}" )
     ZKL_EMIT_FILE_NAMES+=( "$file_name" )
-    ZKL_EMIT_DESCRIPTIONS+=( "" )
+    ZKL_EMIT_DESCRIPTIONS+=( "$desc" )
 }
 
 #
