Earlier check for duplicates in current zekyll

diff --git a/zekylls_regenerate b/zekylls_regenerate
--- a/zekylls_regenerate
+++ b/zekylls_regenerate
@@ -67,6 +67,12 @@ zekylls_string="${zekylls_string//_/}"
 pinfo2 "Read: $zekylls_string"
 print
 
+local -a zekylls1
+zekylls1=( ${(@s:_:)${zekylls_string//(#b)([a-zA-Z0-9][a-zA-Z0-9])/$match[1]_}} )
+
+pinfo "Checking current zekyll for duplicates.."
+detect_duplicates "${zekylls1[@]}" || { echo "Duplicates found, aborting"; exit 1 }
+
 integer lena="${#zekylls_string}"
 
 local new_string_vis=""
@@ -114,12 +120,7 @@ while (( 1 )); do
     fi
 done
 
-local -a zekylls1 zekylls2
-zekylls1=( ${(@s:_:)${zekylls_string//(#b)([a-zA-Z0-9][a-zA-Z0-9])/$match[1]_}} )
-
-pinfo "Checking current zekyll for duplicates.."
-detect_duplicates "${zekylls1[@]}" || { echo "Duplicates found, aborting"; exit 1 }
-
+local -a zekylls2
 zekylls2=( ${(@s:_:)${new_string//(#b)([a-zA-Z0-9][a-zA-Z0-9])/$match[1]_}} )
 
 pinfo "Checking new zekyll for duplicates.."
